---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
      
---
spring:
  profiles: web-subject
words: I,You,He,She,It

---
spring:
  profiles: web-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: web-article
words: a,the

---
spring:
  profiles: web-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: web-noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
subjectServiceName: lab4-spring-web-subject
verbServiceName: lab4-spring-web-verb
articleServiceName: lab4-spring-web-article
adjectiveServiceName: lab4-spring-web-adjective
nounServiceName: lab4-spring-web-noun
